"""Pydantic models for API request/response validation"""

from .mesh import (
    AnalyzeRequest,
    AnalyzeResponse,
    BuildMeshRequest,
    BuildMeshResponse,
    ImproveMeshRequest,
    ImproveMeshResponse,
    CompareRequest,
    CompareResponse,
)
from .research import (
    CompetitorAnalysisRequest,
    CompetitorAnalysisResponse,
)
from .project import (
    Framework,
    PackageManager,
    OnboardingStatus,
    TechStackDetection,
    ContentDirectoryConfig,
    ProjectConfigOverrides,
    ProjectSettings,
    Project,
    OnboardProjectRequest,
    OnboardProjectResponse,
    AnalyzeProjectRequest,
    ConfirmProjectRequest,
    UpdateProjectRequest,
    ProjectDetectionResult,
    ProjectResponse,
    ProjectListResponse,
)
from .images import (
    GenerateImagesRequest,
    GenerateImagesResponse,
    GeneratedImageResponse,
    UploadImageRequest,
    UploadImageResponse,
    OptimizerStatusResponse,
    ImageRobotHistoryResponse,
    ImageProfileData,
    CreateImageProfileRequest,
    ListImageProfilesResponse,
    GenerateImageFromProfileRequest,
    GenerateImageFromProfileResponse,
)

__all__ = [
    # Mesh models
    "AnalyzeRequest",
    "AnalyzeResponse",
    "BuildMeshRequest",
    "BuildMeshResponse",
    "ImproveMeshRequest",
    "ImproveMeshResponse",
    "CompareRequest",
    "CompareResponse",
    # Research models
    "CompetitorAnalysisRequest",
    "CompetitorAnalysisResponse",
    # Project models
    "Framework",
    "PackageManager",
    "OnboardingStatus",
    "TechStackDetection",
    "ContentDirectoryConfig",
    "ProjectConfigOverrides",
    "ProjectSettings",
    "Project",
    "OnboardProjectRequest",
    "OnboardProjectResponse",
    "AnalyzeProjectRequest",
    "ConfirmProjectRequest",
    "UpdateProjectRequest",
    "ProjectDetectionResult",
    "ProjectResponse",
    "ProjectListResponse",
    # Image models
    "GenerateImagesRequest",
    "GenerateImagesResponse",
    "GeneratedImageResponse",
    "UploadImageRequest",
    "UploadImageResponse",
    "OptimizerStatusResponse",
    "ImageRobotHistoryResponse",
    "ImageProfileData",
    "CreateImageProfileRequest",
    "ListImageProfilesResponse",
    "GenerateImageFromProfileRequest",
    "GenerateImageFromProfileResponse",
]
